# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# basic settings
title: "RyanCV - CV / Resume Jekyll Theme"
email: "your-email@example.com"
description: "Jekyll Resume / CV / vCard template"
author: "Admin"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%b %d, %Y"

# paginations & permalinks
paginate: 4
paginate_path: "/page:num/"
permalink: pretty

# disqus comments
disqus_comments: "yes" # yes - show disqus comments, no - hide disqus comments
disqus_shortname: "ryancv-jekyll-theme" # read more here https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

# formsubmit.io
formsubmit_email: "beshleyweb@gmail.com" # sign up on https://formsubmit.io/ and confirm your email

# google maps
google_maps_api_key: "AIzaSyDz2w7HUaWudHwd7AWQpCL48Qs050WOn9s" #google maps api key
google_maps_lat: "40.773328" #google maps latitude
google_maps_long: "-73.960088" #google maps longitude
google_maps_zoom: "14" #google maps zoom

# collections
collections:
  - works

# archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Build settings
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

sass:
  style: compressed

markdown:  kramdown